### ISSUE TITLE
 CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ronlynes** [r4dl/StopThePop#2]
Hi, when I try images at 3k, it will be run out of memory.

Is there anyway to fix and reduce memory size of your rasterizer?

This did not happen in the original rasterizer of 3D GS

**Comment by steimich96** [comment]
Compared to 3DGS, our method should not consume that much more memory, so I guess you were pretty on the edge to begin with? And you use a GPU with 24 GB VRAM?

One option is of course to downscale your images before training. You can call `convert.py` with `--resize` to achieve this.
For other tips, see the [3DGS FAQ](https://github.com/graphdeco-inria/gaussian-splatting?tab=readme-ov-file#faq)
