### ISSUE TITLE
Popping Metric Video Paths

### ISSUE THREAD

**Issue by half-potato** [r4dl/StopThePop#3]
Are the popping metric video paths available? I'm looking to replicate the evaluation.

**Comment by r4dl** [comment]
Hi,
we have not added the files to the repository (yet).
However, [here](https://drive.google.com/file/d/1WO13Uq-fdXkyaqekKt3jiin1630_4kCf/view?usp=sharing) is a link to all videos path we used. In our final evaluation, we only took the results for `r1`, `r2`, ` comb1`.

**Comment by half-potato** [comment]
How did you go about removing the consecutive frames without camera motion?

**Comment by r4dl** [comment]
We did it manually - however, you should be able to do something similar with python (i.e. delete frame if absolute difference to the consecutive frame < `some_small_constant`).

**Comment by half-potato** [comment]
Do you have the frame ids?

**Comment by half-potato** [comment]
Also, what RAFT model did you use? And what happens if you don't skip frames with no motion?

**Comment by r4dl** [comment]
We used RAFT-sintel, as specified in Appendix C (thank you for the observation, this should be mentioned in the README).
When you don't skip frames without metrics, the metrics will be lower than reported (for both 3DGS and Ours), as there will be a very insignificant warping error without motion, thus low FLIP errors.
