### ISSUE TITLE
Encountered error while trying to install package. ╰─> diff_gaussian_rasterization

### ISSUE THREAD

**Issue by YingjianYu** [r4dl/StopThePop#4]
When  I installed the diff_gaussian_rasterization, I encounted the following error information and the installation failed.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /home/sot/projects/win_projects/StopThePop-Rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff_gaussian_rasterization
  Building wheel for diff_gaussian_rasterization (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [2057 lines of output]
........
RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  Running setup.py clean for diff_gaussian_rasterization
Failed to build diff_gaussian_rasterization
Installing collected packages: diff_gaussian_rasterization
  Running setup.py install for diff_gaussian_rasterization ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for diff_gaussian_rasterization did not run successfully.
  │ exit code: 1
  ╰─> [2072 lines of output]
      running install
      /home/sot/anaconda3/envs/stopthepop/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
...................
 RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> diff_gaussian_rasterization

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by r4dl** [comment]
Hi, we can't help you out with the given details. Are there any errors reported during compilation?

**Comment by YingjianYu** [comment]
Hi, the errors reported during compilation are in the attached file.
[output.txt](https://github.com/user-attachments/files/15908152/output.txt)

**Comment by steimich96** [comment]
Which CUDA and gcc version are you using?

Also, please try setting some extra compile arguments [here](https://github.com/r4dl/StopThePop-Rasterization/blob/d8cad09919ff49b11be3d693d1e71fa792f559bb/setup.py#L30) to enable C++17 features:

```
            extra_compile_args={
                "cxx": ["-std=c++17"],
                "nvcc":
                [
                    "-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/"),
                    "-std=c++17"
                ]
            }
```

Please let us know if that worked for you.

**Comment by YingjianYu** [comment]
> Which CUDA and gcc version are you using?
> 
> Also, please try setting some extra compile arguments [here](https://github.com/r4dl/StopThePop-Rasterization/blob/d8cad09919ff49b11be3d693d1e71fa792f559bb/setup.py#L30) to enable C++17 features:
> 
> ```
>             extra_compile_args={
>                 "cxx": ["-std=c++17"],
>                 "nvcc":
>                 [
>                     "-I" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "third_party/glm/"),
>                     "-std=c++17"
>                 ]
>             }
> ```
> 
> Please let us know if that worked for you.

I  am using CUDA 11.3 and gcc 9.4. Still failed.  CUDA 11.3 supports GCC 10.0.0 at the highest level . That is to say, cuda11.3 does not support c++17, and further compilation cannot be successful. Due to the complexity of changing the CUDA version, could you provide a program that does not require such a high C++version？

**Comment by steimich96** [comment]
We have currently no plans to backport this to older CUDA versions.
You will sadly have to do this yourself or update your CUDA version.

**Comment by YingjianYu** [comment]
I updated my cudatoolkit to 11.6 and g++ (gcc) to 11.4, which support the c++ 17, but I still can't install the diff-gaussian-rasterization.

**Comment by steimich96** [comment]
That is strange. You can try deleting the `submodules/diff-gaussian-rasterization/build` folder before rebuilding.

**Comment by YingjianYu** [comment]
Thanks. Could you please tell me what version of cuda toolkit and g++ you use？

**Comment by trThanhnguyen** [comment]
Hi @YingjianYu , have you solved this issue? I'm encountering the same problem. I used CUDA 11.6 and g++-9. Thank you in advance.

**Comment by YingjianYu** [comment]
> Hi [@YingjianYu](https://github.com/YingjianYu) , have you solved this issue? I'm encountering the same problem. I used CUDA 11.6 and g++-9. Thank you in advance.

not yet
