### ISSUE TITLE
Question for the poping artifact

### ISSUE THREAD

**Issue by SYSUykLin** [r4dl/StopThePop#5]
Hello:
    Great paper!
    Has this issue occurred in previous point cloud rendering work(ADOP, NBPG, NBPG++)? But I only saw this issue on this paper. Did the previous point cloud rendering work solve this issue because it used a network(ADOP, NBPG, NBPG++)?
  Thanks!!

**Comment by SYSUykLin** [comment]
And I think of another sorting method (may be foolish). First, sort based on camera rays, and then take out the top N Gaussians. Sort these N Gaussians on each pixel ray. Is this practicable?

**Comment by steimich96** [comment]
The popping problem is especially noticable for 3DGS, as the 3D Gaussians are non-spherical and can show a large range of depth values along different pixel rays in the image. For spherical points this is not an issue, as the range of depth values is minimal.

For your second question: 3DGS already sorts all Gaussians by their view-space z-depth, i.e. the projection of their mean onto the camera ray. If you throw away all but the top N Gaussians, some pixels might be missing important information. You would have to come up with a more sophisticated approach for this to work. Maybe this assumption could be good enough on a per-tile level.

**Comment by SYSUykLin** [comment]
Thanks for your reply. I understand the second answer. But I still confuse the first.

In figure 2:
![image](https://github.com/r4dl/StopThePop/assets/34080744/df90efe5-6ce5-4ec7-9a4a-b87fef14ed80)
If we represent a scene by one-pixel point, eg. ADOP, the order of the points $u_1, u_2$ will still change. 
For example, in case b, $u_1, u_2$, but in case c, $u_2, u_1$. If these two points project to one pixel, it will be a problem.

**Comment by steimich96** [comment]
For traditional one-pixel point splatting, we are speaking of infinitesimally small points in 3D space. As these do not exhibit any depth range, this problem cannot occur. They might still change order globally, but they cannot influence each other. I could imagine that spatially very close points could still lead to a pixel flipping color, but I would not call this popping, but rather flickering.

Also, they probably sort points by their distance to the camera (instead of view-space z-depth). In this scenario, 3DGS also has no popping for camera rotation, but instead for translation.

**Comment by SYSUykLin** [comment]
Thank you for your reply, sorry to bother you for so long.
“I could imagine that spatially very close points could still lead to a pixel flipping color, but I would not call this popping, but rather flickering.”  
Can I understand it as: When two points are very close to each other but project onto the same pixel, using  view-space z-depth to sort will result in a sudden change in order?

**Comment by SYSUykLin** [comment]
In fact, I'm quite puzzled as to why there hasn't been any previous work combining Gaussian splatting with one-pixel point clouds, that is, replacing Gaussian points with **opaque** point cloud rendering, while also incorporating densification and pruning strategies.
