### ISSUE TITLE
Regarding First-Order Linear Search Issues

### ISSUE THREAD

**Issue by will-zzy** [r4dl/StopThePop#8]
Thank you for open-sourcing your excellent work! I have a question concerning line 165 in cuda_rasterizer/stopthepop/stopthepop_common.cuh: The computation of tx as described in the supplementary materials of the paper is:
![340084932-507d319a-b666-43ae-b95f-f6e455e29a5d](https://github.com/user-attachments/assets/c7c03f29-22cb-4a2b-8d74-d7b970659ee7)

where $\mathbf{dx}=[dx,0],(\mu_2-\hat{\mathbf{p}})=[diffx,diffy]$ in my understanding.
So $\Sigma^{-1}=\frac{1}{ac-b^2}matrix([c,-b;-b,a])$.
so the numerator should be $c\cdot dx\cdot diffx-b\cdot dx\cdot diffy$

However, this seems inconsistent with what is on line 165. Could you please explain why this is the case?
`const float tx = not_in_y_range * __saturatef((dx * co.x * diffx + dx * co.y * diffy) * rcp_dxdxcox);`
Thanks for a lot!

**Comment by steimich96** [comment]
Note that 'co' (or also noted as conic) is already the inverse 2D covariance matrix. This should clear up the confusion
