### ISSUE TITLE
Depth for loss computation

### ISSUE THREAD

**Issue by joaxkal** [r4dl/StopThePop#9]
Thank you for the great work!

Rasterizer returns depth rgb, how could I render depth for regularization with gt?

**Comment by steimich96** [comment]
We currently do not have any plans to integrate this.

Feel free to fork the repository and add this yourself. Should be quite easy to pass an additional Tensor from python (or create it in cpp), forward it all the way to the hierarchical rasterization kernel, and set it in the [fin function](https://github.com/r4dl/StopThePop-Rasterization/blob/d8cad09919ff49b11be3d693d1e71fa792f559bb/cuda_rasterizer/stopthepop/hierarchical_render.cuh#L1014).
